### ISSUE TITLE
Match case button in the search dialog same color whether selected or not

### ISSUE THREAD

**Issue by awfki** [lazercaveman/obsidian-firefly-theme#18]
In the "Search in all files" dialog  the Match case button gives no indication of whether that option is enabled. 

I like the theme a lot but search wasn't finding things that I could manually and the (Aa) button didn't look like it was selected.

**Comment by lazercaveman** [comment]
Thank you for reaching out - I will fix that - should be changed within the next update. ✌️

**Comment by lazercaveman** [comment]
🎉 Done - it should be fixed now! : )
